version: '3.1'
services:
  frontend:
    build: .
    image: frontend-img
    container_name: frontend-server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
    command: npm run serve
    networks:
      - app-backend_net_service

networks:
  app-backend_net_service:
    external: true